[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"
