[phases.setup]
nixPkgs = [
  "php84",
  "php84Extensions.gd",
  "php84Extensions.mbstring",
  "php84Extensions.bcmath",
  "php84Extensions.pdo",
  "php84Extensions.pdo_mysql"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
